### ISSUE TITLE
xclim issue calculating percentiles

### ISSUE THREAD

**Issue by ngben** [AusClimateService/BARPA_evaluation#2]
Calculating percentiles in xclim gives the following error. This occurs for at least the following percentiles: TX90p, TX10p, TN90p, TN10p, R95p, R99p. 

```
apply_xclim.xclim_for_agcd(xclim.indicators.icclim.TN90p, "tmin", "mean", years, "./")

 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data/xv83/bxn599/CaRSA/barpa/apply_xclim.py", line 57, in xclim_for_agcd
    new = indicator(ds, freq='M')
  File "/home/599/bxn599/.local/lib/python3.9/site-packages/xclim/core/indicator.py", line 807, in __call__
    das, params = self._parse_variables_from_call(args, kwds)
  File "/home/599/bxn599/.local/lib/python3.9/site-packages/xclim/core/indicator.py", line 891, in _parse_variables_from_call
    self._assign_named_args(ba)
  File "/home/599/bxn599/.local/lib/python3.9/site-packages/xclim/core/indicator.py", line 928, in _assign_named_args
    raise ValueError(
ValueError: Passing variable names as string requires giving the `ds` dataset (got tasmin_per='tasmin_per')
```

**Comment by chunhsusu** [comment]
@ngben  The implementation in `apply_xclim.py` (originally from EH) does not extend easily to allow extra arguments such as percentile. Instead, I have re-implemented with `lib/apply_xclim_gen.py` - this implementation would be easier to be extended to other indicators. I have also added this page, https://github.com/AusClimateService/BARPA_evaluation/blob/main/monthly_metrics.md  to show you what I have tested so far.

You can refer to `chs/examples_apply_xclim_gen.ipynb` to see how I use `lib/apply_xclim_gen.py`. 

I have tried to get `apply_xclim_gen.py` to run indicator=tn10p, tx10p, tx90p, tx10p, but the xclim is giving me results that I could not yet understood. So I label it as untested.

**Comment by ngben** [comment]
Thanks @chunhsusu, I have tried running ```apply_xclim_gen.py``` with the following code:

```python
years = np.arange(2000,2015,1)
apply_xclim_gen.run_xclim("rx1day", "agcd", years, freq="MS", outpath="./")
apply_xclim_gen.run_xclim("tn10p", "agcd", years, freq="MS", outpath="./")
apply_xclim_gen.run_xclim("tx10p", "agcd", years, freq="MS", outpath="./")
apply_xclim_gen.run_xclim("tn90p", "agcd", years, freq="MS", outpath="./")
apply_xclim_gen.run_xclim("tx90p", "agcd", years, freq="MS", outpath="./")
```

Output from the above code is as follows:
```
{'var': 'precip', 'agg': 'calib', 'units': 'mm/day'}
Setting units to mm/day
/home/599/bxn599/.local/lib/python3.9/site-packages/xclim/core/cfchecks.py:44: UserWarning: Variable has a non-conforming cell_methods: Got `time: sum`, which do not include the expected `time: mean`
  _check_cell_methods(
/home/599/bxn599/.local/lib/python3.9/site-packages/xclim/core/cfchecks.py:48: UserWarning: Variable has a non-conforming standard_name: Got `lwe_thickness_of_precipitation_amount`, expected `['precipitation_flux']`
  check_valid(vardata, "standard_name", data["standard_name"])
Written to ./rx1day.agcd_MS_200001-201412.nc
{'var': 'tmin', 'agg': 'mean', 'units': 'degC'}
Setting units to degC
Compute percentile 10 with extracted data
/home/599/bxn599/.local/lib/python3.9/site-packages/xarray/core/indexing.py:1374: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]
/home/599/bxn599/.local/lib/python3.9/site-packages/xarray/core/dataset.py:4652: PerformanceWarning: Reshaping is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array.reshape(shape)

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array.reshape(shape)Explictly passing ``limit`` to ``reshape`` will also silence this warning
    >>> array.reshape(shape, limit='128 MiB')
  result = result._unstack_full_reindex(
/home/599/bxn599/.local/lib/python3.9/site-packages/xarray/core/dataset.py:4351: PerformanceWarning: Reshaping is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array.reshape(shape)

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array.reshape(shape)Explictly passing ``limit`` to ``reshape`` will also silence this warning
    >>> array.reshape(shape, limit='128 MiB')
  result = result._stack_once(dims, new_dim, index_cls, create_index)
/home/599/bxn599/.local/lib/python3.9/site-packages/xarray/core/indexing.py:1374: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]
Written to ./tn10p.agcd_MS_200001-201412.nc
Traceback (most recent call last):
  File "/g/data/xv83/bxn599/CaRSA/barpa/calculate_using_xclim_gen.py", line 17, in <module>
    apply_xclim_gen.run_xclim("tx10p", "agcd", years, freq="MS", outpath="./")
  File "/g/data/xv83/bxn599/CaRSA/barpa/apply_xclim_gen.py", line 365, in run_xclim
    ds = ds.chunk(dict(time=-1))
UnboundLocalError: local variable 'ds' referenced before assignment
```

It seems to fail on tx10p around line 365 in ```apply_xclim_gen.py```, possibly because tx10p and tn90p are missing from lines 310 and 303, respectively?

I also had a look at the tn10p output and it seems that the coordinates aren't in the usual order (time, lat, lon) and are ordered (lat, lon, time). I still need to compare tn10p output with climpact or another tool like NCL.

**Comment by chunhsusu** [comment]
@ngben I have now fixed the obvious bug you raised for tn90p and tx10p. Yes, please check whether what xclim computes make sense when compare with climpact etc.

**Comment by ngben** [comment]
Closing this issue as we are using icclim
